using FluentValidation;
using OAS.Application.Purchasing.Common;
using OAS.Application.Purchasing.PurchaseInvoices.Commands;

namespace OAS.Application.Purchasing.PurchaseInvoices.Validators;

public sealed class CreatePurchaseInvoiceCommandValidator:AbstractValidator<CreatePurchaseInvoiceCommand>
{
    public CreatePurchaseInvoiceCommandValidator(){RuleFor(x=>x.Request.SupplierId).NotEmpty();RuleFor(x=>x.Request.CurrencyId).NotEmpty();RuleFor(x=>x.Request.TaxCalculationMode).IsInEnum();RuleFor(x=>x.Request.ExchangeRate).GreaterThan(0);RuleFor(x=>x.Request.SupplierInvoiceCode).MaximumLength(100);RuleFor(x=>x.Request.Lines).NotEmpty().Must(x=>x.Select(y=>y.LineSequence).Distinct().Count()==x.Count).WithErrorCode("duplicate_line_sequence");RuleForEach(x=>x.Request.Lines).ChildRules(l=>{l.RuleFor(x=>x.LineSequence).GreaterThan(0);l.RuleFor(x=>x.ProductVariantId).NotEmpty();l.RuleFor(x=>x.Quantity).GreaterThan(0);l.RuleFor(x=>x.UnitPrice).GreaterThanOrEqualTo(0);l.RuleFor(x=>x.DiscountAmount).GreaterThanOrEqualTo(0);l.RuleFor(x=>x.TaxRate).GreaterThanOrEqualTo(0);});}
}
public sealed class UpdatePurchaseInvoiceCommandValidator:AbstractValidator<UpdatePurchaseInvoiceCommand>
{
    public UpdatePurchaseInvoiceCommandValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Request.RowVersion).Must(PurchasingRowVersion.IsValid).WithErrorCode("row_version_invalid");RuleFor(x=>x.Request.SupplierId).NotEmpty();RuleFor(x=>x.Request.CurrencyId).NotEmpty();RuleFor(x=>x.Request.TaxCalculationMode).IsInEnum();RuleFor(x=>x.Request.ExchangeRate).GreaterThan(0);RuleFor(x=>x.Request.SupplierInvoiceCode).MaximumLength(100);RuleFor(x=>x.Request.Lines).NotEmpty().Must(x=>x.Select(y=>y.LineSequence).Distinct().Count()==x.Count).WithErrorCode("duplicate_line_sequence");RuleForEach(x=>x.Request.Lines).ChildRules(l=>{l.RuleFor(x=>x.LineSequence).GreaterThan(0);l.RuleFor(x=>x.ProductVariantId).NotEmpty();l.RuleFor(x=>x.Quantity).GreaterThan(0);l.RuleFor(x=>x.UnitPrice).GreaterThanOrEqualTo(0);l.RuleFor(x=>x.DiscountAmount).GreaterThanOrEqualTo(0);l.RuleFor(x=>x.TaxRate).GreaterThanOrEqualTo(0);l.RuleFor(x=>x.RowVersion).Must(v=>v is null||PurchasingRowVersion.IsValid(v)).WithErrorCode("row_version_invalid");});}
}
public sealed class MatchPurchaseInvoiceCommandValidator:AbstractValidator<MatchPurchaseInvoiceCommand>{public MatchPurchaseInvoiceCommandValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Request.RowVersion).Must(PurchasingRowVersion.IsValid);RuleFor(x=>x.Request.Allocations).NotEmpty().Must(x=>x.Select(y=>new{y.PurchaseInvoiceLineId,y.PurchaseReceiptLineId}).Distinct().Count()==x.Count).WithErrorCode("duplicate_match_allocation");RuleForEach(x=>x.Request.Allocations).ChildRules(a=>{a.RuleFor(x=>x.PurchaseInvoiceLineId).NotEmpty();a.RuleFor(x=>x.PurchaseReceiptLineId).NotEmpty();a.RuleFor(x=>x.MatchedQuantity).GreaterThan(0);});}}
public sealed class ConfirmPurchaseInvoiceCommandValidator:AbstractValidator<ConfirmPurchaseInvoiceCommand>{public ConfirmPurchaseInvoiceCommandValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Request.RowVersion).Must(PurchasingRowVersion.IsValid);}}
public sealed class ApprovePurchaseVarianceCommandValidator:AbstractValidator<ApprovePurchaseVarianceCommand>{public ApprovePurchaseVarianceCommandValidator(){RuleFor(x=>x.InvoiceId).NotEmpty();RuleFor(x=>x.Request.AllocationId).NotEmpty();RuleFor(x=>x.Request.ApprovalReason).NotEmpty().MaximumLength(500);RuleFor(x=>x.Request.AllocationRowVersion).Must(PurchasingRowVersion.IsValid);RuleFor(x=>x.Request.InvoiceRowVersion).Must(PurchasingRowVersion.IsValid);}}
public sealed class RejectPurchaseVarianceCommandValidator:AbstractValidator<RejectPurchaseVarianceCommand>{public RejectPurchaseVarianceCommandValidator(){RuleFor(x=>x.InvoiceId).NotEmpty();RuleFor(x=>x.Request.AllocationId).NotEmpty();RuleFor(x=>x.Request.Reason).NotEmpty().MaximumLength(500);RuleFor(x=>x.Request.AllocationRowVersion).Must(PurchasingRowVersion.IsValid);RuleFor(x=>x.Request.InvoiceRowVersion).Must(PurchasingRowVersion.IsValid);}}
public sealed class PostPurchaseInvoiceCommandValidator:AbstractValidator<PostPurchaseInvoiceCommand>{public PostPurchaseInvoiceCommandValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Request.RowVersion).Must(PurchasingRowVersion.IsValid);}}
public sealed class CancelPurchaseInvoiceCommandValidator:AbstractValidator<CancelPurchaseInvoiceCommand>{public CancelPurchaseInvoiceCommandValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Request.Reason).MaximumLength(500);RuleFor(x=>x.Request.RowVersion).Must(PurchasingRowVersion.IsValid);}}
