using OAS.Contracts.Sales.Enums;

namespace OAS.Contracts.Sales.SalesInvoices;

public sealed record SalesInvoiceLineDto(
    Guid Id,
    Guid SalesInvoiceId,
    int LineNumber,
    Guid? CustomerOrderLineId,
    Guid? GroupId,
    SalesLineType LineType,
    Guid? ProductVariantId,
    Guid? WarehouseId,
    string? ProductCodeSnapshot,
    string ProductNameSnapshot,
    string DescriptionSnapshot,
    string? UnitSnapshot,
    decimal Quantity,
    decimal BaseUnitPrice,
    decimal ActualUnitPrice,
    SalesDiscountType DiscountType,
    decimal? DiscountValue,
    decimal DiscountAmount,
    decimal? TaxRate,
    decimal TaxAmount,
    decimal NetAmount,
    decimal FinalAmount,
    decimal BaseNetAmount,
    decimal BaseTaxAmount,
    decimal BaseFinalAmount,
    decimal? UnitCostSnapshot,
    decimal? TotalCostSnapshot,
    Guid? PrescriptionRevisionId,
    EyeSide? PrescriptionEye,
    bool RequiresProduction,
    string? Notes,
    bool IsActive,
    string RowVersion,
    SalesInvoiceLinePrescriptionSnapshotDto? PrescriptionSnapshot,
    string? WarehouseCode = null,
    string? WarehouseName = null,
    string? PrescriptionCode = null,
    int? PrescriptionRevisionNumber = null);
