<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OAS.Print.Desktop</RootNamespace>
    <AssemblyName>OAS.Print</AssemblyName>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OAS.Printing.Core\OAS.Printing.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Templates\*.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="SampleData\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
