/*
    OAS Inventory Transactions — Manual QA Verification

    1) ضع رقم العملية التي أنشأتها من الواجهة في @TransactionNumber.
    2) نفّذ السكربت قبل Post ثم بعد Post وقارن النتائج.
    3) القيم الحالية للـEnums:
       InventoryTransactionStatus: Draft=1, Posted=2
       InventoryMovementType: In=1, Out=2
       InventoryTransactionType:
       Opening=1, Receipt=2, Issue=3, Transfer=4,
       AdjustmentIncrease=5, AdjustmentDecrease=6,
       SalesReturn=7, PurchaseReturn=8, ProductionIssue=9, Scrap=10
*/

SET NOCOUNT ON;

DECLARE @TransactionNumber nvarchar(32) = N'TXN-REPLACE-ME';

DECLARE @TransactionId uniqueidentifier;
SELECT @TransactionId = Id
FROM dbo.tbl_InventoryTransactions
WHERE TransactionNumber = @TransactionNumber;

IF @TransactionId IS NULL
BEGIN
    THROW 50001, 'TransactionNumber was not found. Update @TransactionNumber and run again.', 1;
END;

PRINT '=== 1. TRANSACTION HEADER ===';
SELECT
    t.Id,
    t.TransactionNumber,
    t.TransactionType,
    CASE t.TransactionType
        WHEN 1 THEN N'Opening'
        WHEN 2 THEN N'Receipt'
        WHEN 3 THEN N'Issue'
        WHEN 4 THEN N'Transfer'
        WHEN 5 THEN N'AdjustmentIncrease'
        WHEN 6 THEN N'AdjustmentDecrease'
        WHEN 7 THEN N'SalesReturn'
        WHEN 8 THEN N'PurchaseReturn'
        WHEN 9 THEN N'ProductionIssue'
        WHEN 10 THEN N'Scrap'
        ELSE N'Unknown'
    END AS TransactionTypeName,
    t.Status,
    CASE t.Status WHEN 1 THEN N'Draft' WHEN 2 THEN N'Posted' ELSE N'Unknown' END AS StatusName,
    t.TransactionDate,
    t.SourceWarehouseId,
    sw.Code AS SourceWarehouseCode,
    sw.NameAr AS SourceWarehouseName,
    t.DestinationWarehouseId,
    dw.Code AS DestinationWarehouseCode,
    dw.NameAr AS DestinationWarehouseName,
    t.ReferenceType,
    t.ReferenceId,
    t.Reason,
    t.Notes,
    t.PostedAtUtc,
    t.PostedBy,
    t.CreatedAtUtc,
    t.CreatedBy,
    t.LastModifiedAtUtc,
    t.LastModifiedBy
FROM dbo.tbl_InventoryTransactions t
LEFT JOIN dbo.tbl_Warehouses sw ON sw.Id = t.SourceWarehouseId
LEFT JOIN dbo.tbl_Warehouses dw ON dw.Id = t.DestinationWarehouseId
WHERE t.Id = @TransactionId;

PRINT '=== 2. TRANSACTION LINES ===';
SELECT
    l.Id AS TransactionLineId,
    l.TransactionId,
    l.ProductVariantId,
    p.ProductCode,
    p.NameAr AS ProductName,
    v.SKU,
    v.Barcode,
    v.VariantName,
    l.Quantity,
    l.UnitCost,
    l.TotalCost,
    ROUND(l.Quantity * l.UnitCost, 2) AS ExpectedRoundedTotal,
    l.Notes
FROM dbo.tbl_InventoryTransactionLines l
JOIN dbo.tbl_ProductVariants v ON v.Id = l.ProductVariantId
JOIN dbo.tbl_Products p ON p.Id = v.ProductId
WHERE l.TransactionId = @TransactionId
ORDER BY p.ProductCode, v.SKU;

PRINT '=== 3. LEDGER GENERATED BY THIS TRANSACTION ===';
SELECT
    g.Id,
    g.SequenceNumber,
    g.TransactionId,
    g.TransactionLineId,
    g.WarehouseId,
    w.Code AS WarehouseCode,
    w.NameAr AS WarehouseName,
    g.ProductVariantId,
    v.SKU,
    g.MovementType,
    CASE g.MovementType WHEN 1 THEN N'In' WHEN 2 THEN N'Out' ELSE N'Unknown' END AS MovementTypeName,
    g.QuantityIn,
    g.QuantityOut,
    g.BalanceAfter,
    g.UnitCost,
    g.AverageCostAfter,
    g.InventoryValueAfter,
    g.MovementDate,
    g.CreatedAtUtc,
    g.CreatedBy
FROM dbo.tbl_InventoryLedger g
JOIN dbo.tbl_Warehouses w ON w.Id = g.WarehouseId
JOIN dbo.tbl_ProductVariants v ON v.Id = g.ProductVariantId
WHERE g.TransactionId = @TransactionId
ORDER BY g.SequenceNumber;

PRINT '=== 4. CURRENT BALANCES FOR WAREHOUSES / VARIANTS USED BY THIS TRANSACTION ===';
;WITH UsedPairs AS
(
    SELECT t.SourceWarehouseId AS WarehouseId, l.ProductVariantId
    FROM dbo.tbl_InventoryTransactions t
    JOIN dbo.tbl_InventoryTransactionLines l ON l.TransactionId = t.Id
    WHERE t.Id = @TransactionId AND t.SourceWarehouseId IS NOT NULL

    UNION

    SELECT t.DestinationWarehouseId, l.ProductVariantId
    FROM dbo.tbl_InventoryTransactions t
    JOIN dbo.tbl_InventoryTransactionLines l ON l.TransactionId = t.Id
    WHERE t.Id = @TransactionId AND t.DestinationWarehouseId IS NOT NULL
)
SELECT
    up.WarehouseId,
    w.Code AS WarehouseCode,
    w.NameAr AS WarehouseName,
    up.ProductVariantId,
    v.SKU,
    p.ProductCode,
    p.NameAr AS ProductName,
    b.OnHandQuantity,
    b.ReservedQuantity,
    b.OnOrderQuantity,
    (b.OnHandQuantity - b.ReservedQuantity) AS AvailableQuantity,
    b.AverageUnitCost,
    b.InventoryValue,
    b.LastMovementAtUtc
FROM UsedPairs up
JOIN dbo.tbl_Warehouses w ON w.Id = up.WarehouseId
JOIN dbo.tbl_ProductVariants v ON v.Id = up.ProductVariantId
JOIN dbo.tbl_Products p ON p.Id = v.ProductId
LEFT JOIN dbo.tbl_InventoryBalances b
    ON b.WarehouseId = up.WarehouseId
   AND b.ProductVariantId = up.ProductVariantId
ORDER BY w.Code, v.SKU;

PRINT '=== 5. AUTOMATIC QA CHECKS ===';
DECLARE @Type int, @Status int, @LineCount int, @LedgerCount int, @ExpectedLedgerCount int;
SELECT @Type = TransactionType, @Status = Status
FROM dbo.tbl_InventoryTransactions
WHERE Id = @TransactionId;

SELECT @LineCount = COUNT(*)
FROM dbo.tbl_InventoryTransactionLines
WHERE TransactionId = @TransactionId;

SELECT @LedgerCount = COUNT(*)
FROM dbo.tbl_InventoryLedger
WHERE TransactionId = @TransactionId;

SET @ExpectedLedgerCount = CASE
    WHEN @Status = 1 THEN 0
    WHEN @Status = 2 AND @Type = 4 THEN @LineCount * 2
    WHEN @Status = 2 THEN @LineCount
    ELSE NULL
END;

SELECT
    @TransactionNumber AS TransactionNumber,
    @Type AS TransactionType,
    @Status AS Status,
    @LineCount AS LineCount,
    @LedgerCount AS LedgerCount,
    @ExpectedLedgerCount AS ExpectedLedgerCount,
    CASE WHEN @LineCount > 0 THEN N'PASS' ELSE N'FAIL: no lines' END AS HasLines,
    CASE WHEN @LedgerCount = @ExpectedLedgerCount THEN N'PASS' ELSE N'FAIL: unexpected ledger count' END AS LedgerCountCheck,
    CASE WHEN NOT EXISTS
    (
        SELECT ProductVariantId
        FROM dbo.tbl_InventoryTransactionLines
        WHERE TransactionId = @TransactionId
        GROUP BY ProductVariantId
        HAVING COUNT(*) > 1
    ) THEN N'PASS' ELSE N'FAIL: duplicate variant lines' END AS DuplicateVariantCheck,
    CASE WHEN NOT EXISTS
    (
        SELECT 1
        FROM dbo.tbl_InventoryTransactionLines
        WHERE TransactionId = @TransactionId
          AND (Quantity <= 0 OR Quantity <> ROUND(Quantity, 3))
    ) THEN N'PASS' ELSE N'FAIL: quantity precision/value' END AS QuantityCheck,
    CASE WHEN NOT EXISTS
    (
        SELECT 1
        FROM dbo.tbl_InventoryTransactionLines
        WHERE TransactionId = @TransactionId
          AND (UnitCost < 0 OR UnitCost <> ROUND(UnitCost, 2))
    ) THEN N'PASS' ELSE N'FAIL: unit cost precision/value' END AS UnitCostCheck,
    CASE WHEN NOT EXISTS
    (
        SELECT 1
        FROM dbo.tbl_InventoryTransactionLines
        WHERE TransactionId = @TransactionId
          AND ABS(TotalCost - ROUND(Quantity * UnitCost, 2)) > 0.01
    ) THEN N'PASS' ELSE N'FAIL: total cost mismatch' END AS TotalCostCheck,
    CASE
        WHEN @Status = 1 AND EXISTS (SELECT 1 FROM dbo.tbl_InventoryLedger WHERE TransactionId = @TransactionId)
            THEN N'FAIL: draft transaction has ledger rows'
        WHEN @Status = 2 AND EXISTS
        (
            SELECT 1
            FROM dbo.tbl_InventoryTransactionLines l
            WHERE l.TransactionId = @TransactionId
              AND
              (
                  (@Type IN (1,2,5,7) AND NOT EXISTS
                      (SELECT 1 FROM dbo.tbl_InventoryLedger g
                       JOIN dbo.tbl_InventoryTransactions tx ON tx.Id = g.TransactionId
                       WHERE g.TransactionId = @TransactionId
                         AND g.TransactionLineId = l.Id
                         AND g.MovementType = 1
                         AND g.WarehouseId = tx.DestinationWarehouseId
                         AND g.QuantityIn = l.Quantity
                         AND g.QuantityOut = 0))
                  OR
                  (@Type IN (3,6,8,9,10) AND NOT EXISTS
                      (SELECT 1 FROM dbo.tbl_InventoryLedger g
                       JOIN dbo.tbl_InventoryTransactions tx ON tx.Id = g.TransactionId
                       WHERE g.TransactionId = @TransactionId
                         AND g.TransactionLineId = l.Id
                         AND g.MovementType = 2
                         AND g.WarehouseId = tx.SourceWarehouseId
                         AND g.QuantityOut = l.Quantity
                         AND g.QuantityIn = 0))
                  OR
                  (@Type = 4 AND
                      (
                          NOT EXISTS
                          (SELECT 1 FROM dbo.tbl_InventoryLedger g
                           JOIN dbo.tbl_InventoryTransactions tx ON tx.Id = g.TransactionId
                           WHERE g.TransactionId = @TransactionId
                             AND g.TransactionLineId = l.Id
                             AND g.MovementType = 2
                             AND g.WarehouseId = tx.SourceWarehouseId
                             AND g.QuantityOut = l.Quantity
                             AND g.QuantityIn = 0)
                          OR NOT EXISTS
                          (SELECT 1 FROM dbo.tbl_InventoryLedger g
                           JOIN dbo.tbl_InventoryTransactions tx ON tx.Id = g.TransactionId
                           WHERE g.TransactionId = @TransactionId
                             AND g.TransactionLineId = l.Id
                             AND g.MovementType = 1
                             AND g.WarehouseId = tx.DestinationWarehouseId
                             AND g.QuantityIn = l.Quantity
                             AND g.QuantityOut = 0)
                      ))
              )
        ) THEN N'FAIL: ledger movement/warehouse/quantity mismatch'
        ELSE N'PASS'
    END AS LedgerMovementCheck,
    CASE
        WHEN @Status = 2 AND EXISTS
            (SELECT 1 FROM dbo.tbl_InventoryTransactions WHERE Id = @TransactionId AND (PostedAtUtc IS NULL OR PostedBy IS NULL))
            THEN N'FAIL: posted audit fields missing'
        ELSE N'PASS'
    END AS PostedAuditCheck;

PRINT '=== 6. HEADER RULE CHECKS ===';
SELECT
    CASE
        WHEN @Type IN (1,2,5,7) AND DestinationWarehouseId IS NULL THEN N'FAIL: destination required'
        WHEN @Type IN (3,6,8,9,10) AND SourceWarehouseId IS NULL THEN N'FAIL: source required'
        WHEN @Type = 4 AND SourceWarehouseId IS NULL THEN N'FAIL: transfer source required'
        WHEN @Type = 4 AND DestinationWarehouseId IS NULL THEN N'FAIL: transfer destination required'
        WHEN @Type = 4 AND SourceWarehouseId = DestinationWarehouseId THEN N'FAIL: transfer warehouses must differ'
        WHEN @Type IN (5,6) AND NULLIF(LTRIM(RTRIM(Reason)), N'') IS NULL THEN N'FAIL: adjustment reason required'
        ELSE N'PASS'
    END AS HeaderRulesCheck
FROM dbo.tbl_InventoryTransactions
WHERE Id = @TransactionId;

/*
Rollback / insufficient-stock test:
- قبل الضغط على Post شغّل القسم 4 وسجّل قيم الأرصدة.
- حاول Post لكمية أكبر من OnHand.
- شغّل السكربت من جديد.
المتوقع:
  Status = 1 (Draft)
  LedgerCount = 0
  الأرصدة مطابقة تمامًا لقيم ما قبل المحاولة.
*/
