using OAS.Contracts.Common.Errors;

namespace OAS.Client.Accounting.Common;

/// <summary>
/// Arabic presentation for expected Accounting business errors.
/// Error codes remain unchanged; unexpected/programming errors are intentionally not mapped here.
/// </summary>
public static class AccountingApiErrorPresenter
{
    private static readonly IReadOnlyDictionary<string, string> Messages =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["accounting_settings_required"] = "يجب إعداد المحاسبة وتحديد العملة الأساسية أولاً.",
            ["base_currency_missing"] = "العملة الأساسية المحددة في إعدادات المحاسبة غير موجودة.",
            ["base_currency_inactive"] = "يجب أن تكون العملة الأساسية نشطة.",
            ["base_currency_change_blocked"] = "لا يمكن تغيير العملة الأساسية بعد وجود قيود محاسبية مرحّلة.",
            ["journal_account_not_manual_postable"] = "الحساب المحدد غير صالح للقيد اليدوي أو لا يسمح بالترحيل اليدوي.",
            ["journal_line_amount_invalid"] = "سطر القيد يجب أن يحتوي مبلغًا موجبًا في المدين أو الدائن فقط.",
            ["journal_lines_missing"] = "يجب إضافة سطر واحد على الأقل إلى القيد.",
            ["journal_party_invalid"] = "يمكن تحديد عميل أو مورد أو موظف واحد فقط في سطر القيد.",
            ["journal_customer_inactive"] = "العميل المحدد غير نشط.",
            ["journal_supplier_inactive"] = "المورد المحدد غير نشط.",
            ["journal_employee_inactive"] = "الموظف المحدد غير نشط.",
            ["account_inactive"] = "الحساب المحدد غير نشط.",
            ["account_not_postable"] = "الحساب المحدد حساب رئيسي أو غير مهيأ لاستقبال الترحيل.",
            ["counterparty_account_invalid"] = "الحساب المقابل غير صالح لهذه العملية.",
            ["settlement_account_invalid"] = "الحساب المحاسبي المرتبط بوسيلة التسوية غير صالح للترحيل.",
            ["other_settlement_account_invalid"] = "حساب التسوية المحدد غير نشط أو لا يسمح بالقيد اليدوي.",
            ["other_settlement_account_required"] = "يجب تحديد حساب التسوية عند استخدام طريقة الدفع «أخرى».",
            ["other_party_account_required"] = "يجب تحديد الحساب المقابل للطرف «أخرى».",
            ["other_party_name_required"] = "اسم الطرف مطلوب عند اختيار نوع الطرف «أخرى».",
            ["other_party_fk_conflict"] = "الطرف «أخرى» لا يمكن ربطه بعميل أو مورد أو موظف في الوقت نفسه.",
            ["typed_party_fk_invalid"] = "الطرف المحدد لا يطابق نوع الطرف في السطر.",
            ["customer_required"] = "يجب تحديد العميل.",
            ["supplier_required"] = "يجب تحديد المورد.",
            ["employee_required"] = "يجب تحديد الموظف.",
            ["customer_inactive"] = "العميل المحدد غير نشط.",
            ["supplier_inactive"] = "المورد المحدد غير نشط.",
            ["employee_inactive"] = "الموظف المحدد غير نشط.",
            ["employee_account_mapping_required"] = "الموظف المحدد لا يملك ربطًا محاسبيًا نشطًا.",
            ["cash_account_inactive"] = "الصندوق المحدد غير نشط.",
            ["bank_account_inactive"] = "الحساب البنكي المحدد غير نشط.",
            ["cash_currency_mismatch"] = "عملة الصندوق لا تطابق عملة سطر السند.",
            ["bank_currency_mismatch"] = "عملة الحساب البنكي لا تطابق عملة سطر السند.",
            ["cash_payment_account_required"] = "يجب تحديد الصندوق عند اختيار الدفع النقدي.",
            ["bank_payment_account_required"] = "يجب تحديد الحساب البنكي لطريقة الدفع المختارة.",
            ["cash_payment_bank_not_allowed"] = "لا يمكن تحديد حساب بنكي مع طريقة الدفع النقدي.",
            ["bank_payment_cash_not_allowed"] = "لا يمكن تحديد صندوق مع طريقة الدفع البنكية.",
            ["other_payment_cash_not_allowed"] = "لا يمكن تحديد صندوق عند استخدام طريقة الدفع «أخرى».",
            ["other_payment_bank_not_allowed"] = "لا يمكن تحديد حساب بنكي عند استخدام طريقة الدفع «أخرى».",
            ["cheque_reference_required"] = "رقم الشيك مطلوب عند اختيار طريقة الدفع بالشيك.",
            ["payment_account_required"] = "يجب تحديد صندوق أو حساب بنكي واحد فقط قبل الترحيل.",
            ["fiscal_period_not_found"] = "لا توجد فترة مالية تغطي تاريخ الترحيل.",
            ["fiscal_period_overlap"] = "يوجد أكثر من فترة مالية تغطي تاريخ الترحيل. راجع إعداد الفترات المالية.",
            ["fiscal_period_closed"] = "لا يمكن الترحيل إلى فترة مالية مغلقة أو مقفلة محاسبيًا.",
            ["exchange_rate_not_found"] = "لا يوجد سعر صرف صالح للعملة والتاريخ المحددين.",
            ["exchange_rate_invalid"] = "سعر الصرف غير صالح.",
            ["exchange_rate_override_forbidden"] = "لا تملك صلاحية إدخال سعر صرف يدوي.",
            ["settlement_amount_invalid"] = "مبلغ سطر التسوية يجب أن يكون أكبر من صفر.",
            ["voucher_lines_required"] = "يجب أن يحتوي السند على سطر واحد على الأقل قبل الاعتماد أو الترحيل.",
            ["voucher_settlement_line_incomplete"] = "توجد أسطر تسوية غير مكتملة. راجع الطرف ووسيلة التسوية والعملة وسعر الصرف.",
            ["voucher_base_total_mismatch"] = "إجمالي السند بالعملة الأساسية لا يطابق مجموع الأسطر.",
            ["receipt_voucher_lines_required"] = "يجب أن يحتوي سند القبض على سطر واحد على الأقل قبل الترحيل.",
            ["payment_voucher_lines_required"] = "يجب أن يحتوي سند الصرف على سطر واحد على الأقل قبل الترحيل.",
            ["receipt_voucher_not_editable"] = "لا يمكن تعديل سند القبض بعد مغادرة حالة المسودة.",
            ["payment_voucher_not_editable"] = "لا يمكن تعديل سند الصرف بعد مغادرة حالة المسودة.",
            ["receipt_status_transition_invalid"] = "انتقال حالة سند القبض المطلوب غير مسموح من الحالة الحالية.",
            ["payment_status_transition_invalid"] = "انتقال حالة سند الصرف المطلوب غير مسموح من الحالة الحالية.",
            ["receipt_voucher_total_invalid"] = "يجب أن يكون إجمالي سند القبض أكبر من صفر.",
            ["payment_voucher_total_invalid"] = "يجب أن يكون إجمالي سند الصرف أكبر من صفر.",
            ["linked_account_parent_invalid"] = "الحساب الرئيسي يجب أن يكون حساب تحكم نشطًا من الأصول بطبيعة مدينة.",
            ["linked_account_parent_code_invalid"] = "كود الحساب الرئيسي يجب أن يكون رقميًا وبطول يسمح بإنشاء الحساب الفرعي.",
            ["cash_parent_account_required"] = "يجب تحديد الحساب الرئيسي للصناديق في إعدادات المحاسبة أولاً.",
            ["bank_parent_account_required"] = "يجب تحديد الحساب الرئيسي للبنوك في إعدادات المحاسبة أولاً.",
            ["employee_parent_account_required"] = "يجب تحديد الحساب الرئيسي لذمم الموظفين في إعدادات المحاسبة أولاً.",
            ["cash_parent_account_invalid"] = "الحساب الرئيسي للصناديق غير صالح.",
            ["bank_parent_account_invalid"] = "الحساب الرئيسي للبنوك غير صالح.",
            ["employee_parent_account_invalid"] = "الحساب الرئيسي لذمم الموظفين غير صالح.",
            ["exchange_gain_account_invalid"] = "حساب أرباح فروق العملة غير صالح للترحيل.",
            ["exchange_loss_account_invalid"] = "حساب خسائر فروق العملة غير صالح للترحيل.",
            ["posting_profile_account_invalid"] = "أحد حسابات ملف الترحيل غير صالح للترحيل الآلي.",
            ["expense_account_invalid"] = "حساب المصروف المحدد غير صالح للترحيل.",
            ["default_expense_account_invalid"] = "الحساب الافتراضي لنوع المصروف غير صالح للترحيل.",
            ["payment_allocation_exceeds_available_amount"] = "مبلغ التخصيص يتجاوز المبلغ المتاح في مصدر الدفعة.",
            ["payment_source_line_required"] = "يجب تحديد سطر واحد من سند قبض أو سند صرف كمصدر للدفعة.",
            ["payment_source_line_not_migrated"] = "سطر مصدر الدفعة قديم ولا يحتوي بيانات التسوية متعددة العملات المطلوبة.",
            ["legacy_allocation_readonly"] = "تخصيص الدفعة القديم للقراءة فقط حتى يتم ترحيل بياناته.",
            ["accounting_managed_account_edit_forbidden"] = "الحساب المُدار آليًا يجب تعديله من شاشة الكيان المرتبط به.",
            ["accounting_managed_account_status_forbidden"] = "حالة الحساب المُدار آليًا يجب تغييرها من شاشة الكيان المرتبط به.",
            ["accounting_account_code_immutable"] = "لا يمكن تغيير كود الحساب بعد إنشائه.",
            ["accounting_posting_profile_code_immutable"] = "لا يمكن تغيير كود ملف الترحيل بعد إنشائه.",
            ["accounting_expense_type_code_immutable"] = "لا يمكن تغيير كود نوع المصروف بعد إنشائه.",
            ["accounting_bank_account_number_immutable"] = "لا يمكن تغيير رقم الحساب البنكي بعد الإنشاء.",
            ["account_level_exhausted"] = "لا يمكن إنشاء مستوى فرعي إضافي تحت الحساب المحدد.",
            ["accounting_account_level_exhausted"] = "لا يمكن إنشاء مستوى فرعي إضافي تحت هذا الحساب.",
            ["accounting_cash_account_code_exhausted"] = "تعذر توليد كود فريد للصندوق. أعد المحاولة أو أدخل كودًا آخر.",
            ["accounting_bank_account_code_exhausted"] = "تعذر توليد كود فريد للحساب البنكي. أعد المحاولة أو أدخل كودًا آخر.",
            ["accounting_cost_center_code_immutable"] = "لا يمكن تغيير كود مركز التكلفة بعد إنشائه.",
            ["accounting_fiscal_year_code_immutable"] = "لا يمكن تغيير كود السنة المالية بعد إنشائها.",
            ["accounting_party_parent_code_invalid"] = "كود الحساب الرئيسي غير صالح لإنشاء الحساب الفرعي.",
            ["accounting_party_parent_not_found"] = "الحساب الرئيسي المحدد غير موجود.",
            ["accounting_customer_parent_invalid"] = "الحساب الرئيسي المحدد غير صالح لحسابات العملاء. يجب أن يكون حساب تحكم نشطًا من الأصول بطبيعة مدينة.",
            ["accounting_supplier_parent_invalid"] = "الحساب الرئيسي المحدد غير صالح لحسابات الموردين. يجب أن يكون حساب تحكم نشطًا من الالتزامات بطبيعة دائنة.",
            ["bank_account_number_duplicate"] = "رقم الحساب البنكي مستخدم مسبقًا.",
            ["bank_currency_inactive"] = "العملة المحددة للحساب البنكي غير نشطة.",
            ["cash_currency_inactive"] = "العملة المحددة للصندوق غير نشطة.",
            ["cash_payment_account_invalid"] = "الحساب المحاسبي المرتبط بالصندوق غير صالح للترحيل.",
            ["bank_payment_account_invalid"] = "الحساب المحاسبي المرتبط بالحساب البنكي غير صالح للترحيل.",
            ["payment_method_invalid"] = "طريقة الدفع المحددة غير مدعومة لهذه العملية.",
            ["settlement_party_type_invalid"] = "نوع الطرف المحدد غير صالح للتسوية.",
            ["receipt_base_currency_missing"] = "بيانات العملة الأساسية المحفوظة مع سند القبض غير مكتملة.",
            ["payment_base_currency_missing"] = "بيانات العملة الأساسية المحفوظة مع سند الصرف غير مكتملة.",
            ["base_currency_rate_must_be_one"] = "سعر صرف العملة الأساسية يجب أن يساوي 1.",
            ["currency_required"] = "يجب تحديد العملة.",
            ["currency_inactive"] = "العملة المحددة غير نشطة.",
            ["currency_code_duplicate"] = "كود العملة مستخدم مسبقًا.",
            ["exchange_rate_currency_inactive"] = "لا يمكن إضافة سعر صرف لعملة غير نشطة.",
            ["exchange_rate_duplicate"] = "يوجد سعر صرف مسجل مسبقًا لنفس العملة والتاريخ ونوع السعر.",
            ["cash_shift_number_duplicate"] = "رقم وردية الصندوق مستخدم مسبقًا.",
            ["cash_shift_number_period_mismatch"] = "رقم وردية الصندوق المحجوز لا يطابق السنة الحالية.",
            ["expense_number_duplicate"] = "رقم المصروف مستخدم مسبقًا.",
            ["expense_number_period_mismatch"] = "رقم المصروف المحجوز لا يطابق سنة المصروف.",
            ["journal_number_duplicate"] = "رقم القيد مستخدم مسبقًا.",
            ["journal_number_period_mismatch"] = "رقم القيد المحجوز لا يطابق سنة الترحيل.",
            ["receipt_voucher_number_duplicate"] = "رقم سند القبض مستخدم مسبقًا.",
            ["receipt_voucher_number_period_mismatch"] = "رقم سند القبض المحجوز لا يطابق سنة السند.",
            ["payment_voucher_number_duplicate"] = "رقم سند الصرف مستخدم مسبقًا.",
            ["payment_voucher_number_period_mismatch"] = "رقم سند الصرف المحجوز لا يطابق سنة السند.",
            ["manual_posting_not_allowed"] = "الحساب المحدد لا يسمح بالقيد اليدوي.",
            ["header_account_posting_not_allowed"] = "لا يمكن الترحيل مباشرة إلى حساب رئيسي.",
            ["journal_not_posted"] = "يمكن عكس القيود المرحّلة فقط.",
            ["fiscal_period_reopen_not_supported"] = "لا يمكن إعادة فتح فترة مالية مغلقة أو مقفلة مبدئيًا بهذه العملية.",
            ["invalid_fiscal_period_status"] = "حالة الفترة المالية المطلوبة غير مدعومة.",
            ["fiscal_year_status_invalid"] = "انتقال حالة السنة المالية المطلوب غير مسموح.",
            ["current_user_required"] = "تعذر تحديد المستخدم الحالي لتنفيذ الإجراء.",
            ["employee_account_exists"] = "لدى الموظف ربط محاسبي موجود مسبقًا.",
            ["accounting_customer_code_duplicate"] = "كود العميل مستخدم مسبقًا.",
            ["accounting_customer_code_exhausted"] = "تعذر توليد كود فريد للعميل.",
            ["accounting_customer_cr_duplicate"] = "رقم السجل التجاري للعميل مستخدم مسبقًا.",
            ["accounting_customer_national_id_duplicate"] = "رقم الهوية للعميل مستخدم مسبقًا.",
            ["accounting_customer_tax_number_duplicate"] = "الرقم الضريبي للعميل مستخدم مسبقًا.",
            ["accounting_supplier_code_duplicate"] = "كود المورد مستخدم مسبقًا.",
            ["accounting_supplier_code_exhausted"] = "تعذر توليد كود فريد للمورد.",
            ["accounting_supplier_cr_duplicate"] = "رقم السجل التجاري للمورد مستخدم مسبقًا.",
            ["accounting_supplier_national_id_duplicate"] = "رقم الهوية للمورد مستخدم مسبقًا.",
            ["accounting_supplier_tax_number_duplicate"] = "الرقم الضريبي للمورد مستخدم مسبقًا."
        };

    public static bool TryGetMessage(ApiError error, out string message)
    {
        ArgumentNullException.ThrowIfNull(error);
        return Messages.TryGetValue(error.Code ?? string.Empty, out message!);
    }
}
