using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OAS.Infrastructure.Persistence;
#nullable disable
namespace OAS.Infrastructure.Persistence.Migrations;
[DbContext(typeof(OasDbContext))]
[Migration("20261003100000_HRPayrollCore")]
public sealed class HRPayrollCore : Migration
{
 protected override void Up(MigrationBuilder m)
 {
  m.Sql("""
SET XACT_ABORT ON;
IF NOT EXISTS(SELECT 1 FROM sys.sequences WHERE name=N'PayrollPolicyCodeSequence' AND schema_id=SCHEMA_ID(N'hr')) EXEC(N'CREATE SEQUENCE [hr].[PayrollPolicyCodeSequence] AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE;');
IF NOT EXISTS(SELECT 1 FROM sys.sequences WHERE name=N'PayrollRunCodeSequence' AND schema_id=SCHEMA_ID(N'hr')) EXEC(N'CREATE SEQUENCE [hr].[PayrollRunCodeSequence] AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE;');
IF COL_LENGTH('hr.EmployeeContracts','TerminationEffectiveDate') IS NULL ALTER TABLE [hr].[EmployeeContracts] ADD [TerminationEffectiveDate] date NULL;

IF OBJECT_ID(N'[hr].[PayrollPolicies]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[PayrollPolicies]([Id] uniqueidentifier NOT NULL,[PolicyCode] nvarchar(32) NOT NULL,[NameAr] nvarchar(150) NOT NULL,[EffectiveFrom] date NOT NULL,[EffectiveTo] date NULL,[Status] tinyint NOT NULL,[ProrationMethod] tinyint NOT NULL,[DailyRateMethod] tinyint NOT NULL,[HourlyRateMethod] tinyint NOT NULL,[RequireApprovedAttendance] bit NOT NULL,[RequireFullPaymentBeforeRunClose] bit NOT NULL,[AbsenceDeductionComponentId] uniqueidentifier NULL,[LateDeductionComponentId] uniqueidentifier NULL,[EarlyLeaveDeductionComponentId] uniqueidentifier NULL,[UnpaidLeaveComponentId] uniqueidentifier NULL,[OvertimeComponentId] uniqueidentifier NULL,[Notes] nvarchar(500) NULL,[ActivatedBy] nvarchar(64) NULL,[ActivatedAtUtc] datetimeoffset NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_PayrollPolicies] PRIMARY KEY([Id]),CONSTRAINT [CK_PayrollPolicies_EffectiveDates] CHECK([EffectiveTo] IS NULL OR [EffectiveTo]>=[EffectiveFrom]),CONSTRAINT [FK_PayrollPolicies_AbsenceComponent] FOREIGN KEY([AbsenceDeductionComponentId]) REFERENCES [hr].[SalaryComponents]([Id]),CONSTRAINT [FK_PayrollPolicies_LateComponent] FOREIGN KEY([LateDeductionComponentId]) REFERENCES [hr].[SalaryComponents]([Id]),CONSTRAINT [FK_PayrollPolicies_EarlyLeaveComponent] FOREIGN KEY([EarlyLeaveDeductionComponentId]) REFERENCES [hr].[SalaryComponents]([Id]),CONSTRAINT [FK_PayrollPolicies_UnpaidLeaveComponent] FOREIGN KEY([UnpaidLeaveComponentId]) REFERENCES [hr].[SalaryComponents]([Id]),CONSTRAINT [FK_PayrollPolicies_OvertimeComponent] FOREIGN KEY([OvertimeComponentId]) REFERENCES [hr].[SalaryComponents]([Id]));
 CREATE UNIQUE INDEX [UX_PayrollPolicies_Code] ON [hr].[PayrollPolicies]([PolicyCode]);CREATE UNIQUE INDEX [UX_PayrollPolicies_OneActive] ON [hr].[PayrollPolicies]([Status]) WHERE [Status] = 2;CREATE INDEX [IX_PayrollPolicies_Status_Dates] ON [hr].[PayrollPolicies]([Status],[EffectiveFrom],[EffectiveTo]);
END;
IF OBJECT_ID(N'[hr].[PayrollPeriods]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[PayrollPeriods]([Id] uniqueidentifier NOT NULL,[PeriodCode] nvarchar(20) NOT NULL,[Year] smallint NOT NULL,[Month] tinyint NOT NULL,[StartDate] date NOT NULL,[EndDate] date NOT NULL,[Status] tinyint NOT NULL,[LockedBy] nvarchar(64) NULL,[LockedAtUtc] datetimeoffset NULL,[ClosedBy] nvarchar(64) NULL,[ClosedAtUtc] datetimeoffset NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_PayrollPeriods] PRIMARY KEY([Id]),CONSTRAINT [CK_PayrollPeriods_Dates] CHECK([EndDate]>=[StartDate] AND [Month] BETWEEN 1 AND 12));
 CREATE UNIQUE INDEX [UX_PayrollPeriods_Code] ON [hr].[PayrollPeriods]([PeriodCode]);CREATE UNIQUE INDEX [UX_PayrollPeriods_Year_Month] ON [hr].[PayrollPeriods]([Year],[Month]);
END;
IF OBJECT_ID(N'[hr].[PayrollRuns]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[PayrollRuns]([Id] uniqueidentifier NOT NULL,[PayrollRunCode] nvarchar(40) NOT NULL,[PayrollPeriodId] uniqueidentifier NOT NULL,[RunType] tinyint NOT NULL,[Status] tinyint NOT NULL,[CalculationDate] date NOT NULL,[PostingDate] date NULL,[PayrollPolicyId] uniqueidentifier NOT NULL,[CurrencyId] uniqueidentifier NOT NULL,[CurrencyCodeSnapshot] nvarchar(8) NOT NULL,[CurrencySymbolSnapshot] nvarchar(12) NULL,[CurrencyDecimalPlacesSnapshot] tinyint NOT NULL,[BaseCurrencyId] uniqueidentifier NULL,[BaseCurrencyCodeSnapshot] nvarchar(8) NULL,[BaseCurrencyDecimalPlacesSnapshot] tinyint NULL,[PostingExchangeRate] decimal(19,8) NULL,[PostingExchangeRateDate] date NULL,[PostingExchangeRateType] tinyint NULL,[PostingExchangeRateSource] tinyint NULL,[TotalGrossEarnings] decimal(19,4) NOT NULL,[TotalDeductions] decimal(19,4) NOT NULL,[TotalEmployerContributions] decimal(19,4) NOT NULL,[TotalNetPay] decimal(19,4) NOT NULL,[BaseGrossEarnings] decimal(19,4) NOT NULL,[BaseDeductions] decimal(19,4) NOT NULL,[BaseEmployerContributions] decimal(19,4) NOT NULL,[BaseNetPay] decimal(19,4) NOT NULL,[JournalEntryId] uniqueidentifier NULL,[CalculatedBy] nvarchar(64) NULL,[CalculatedAtUtc] datetimeoffset NULL,[ReviewedBy] nvarchar(64) NULL,[ReviewedAtUtc] datetimeoffset NULL,[ApprovedBy] nvarchar(64) NULL,[ApprovedAtUtc] datetimeoffset NULL,[PostedBy] nvarchar(64) NULL,[PostedAtUtc] datetimeoffset NULL,[ClosedBy] nvarchar(64) NULL,[ClosedAtUtc] datetimeoffset NULL,[Notes] nvarchar(1000) NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_PayrollRuns] PRIMARY KEY([Id]),CONSTRAINT [CK_PayrollRuns_Totals] CHECK([TotalGrossEarnings]>=0 AND [TotalDeductions]>=0 AND [TotalEmployerContributions]>=0 AND [TotalNetPay]>=0 AND [BaseGrossEarnings]>=0 AND [BaseDeductions]>=0 AND [BaseEmployerContributions]>=0 AND [BaseNetPay]>=0),CONSTRAINT [CK_PayrollRuns_PostingRate] CHECK([PostingExchangeRate] IS NULL OR [PostingExchangeRate]>0),CONSTRAINT [FK_PayrollRuns_Period] FOREIGN KEY([PayrollPeriodId]) REFERENCES [hr].[PayrollPeriods]([Id]),CONSTRAINT [FK_PayrollRuns_Policy] FOREIGN KEY([PayrollPolicyId]) REFERENCES [hr].[PayrollPolicies]([Id]),CONSTRAINT [FK_PayrollRuns_Currency] FOREIGN KEY([CurrencyId]) REFERENCES [dbo].[tbl_Currencies]([Id]),CONSTRAINT [FK_PayrollRuns_BaseCurrency] FOREIGN KEY([BaseCurrencyId]) REFERENCES [dbo].[tbl_Currencies]([Id]),CONSTRAINT [FK_PayrollRuns_Journal] FOREIGN KEY([JournalEntryId]) REFERENCES [dbo].[tbl_JournalEntries]([Id]));
 CREATE UNIQUE INDEX [UX_PayrollRuns_Code] ON [hr].[PayrollRuns]([PayrollRunCode]);CREATE UNIQUE INDEX [UX_PayrollRuns_Period_Currency_Type_Active] ON [hr].[PayrollRuns]([PayrollPeriodId],[CurrencyId],[RunType]) WHERE [Status] <> 7;CREATE INDEX [IX_PayrollRuns_Period_Status] ON [hr].[PayrollRuns]([PayrollPeriodId],[Status]);CREATE INDEX [IX_PayrollRuns_Currency] ON [hr].[PayrollRuns]([CurrencyId]);
END;
IF OBJECT_ID(N'[hr].[EmployeePayrolls]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[EmployeePayrolls]([Id] uniqueidentifier NOT NULL,[PayrollRunId] uniqueidentifier NOT NULL,[PayrollPeriodId] uniqueidentifier NOT NULL,[EmployeeId] uniqueidentifier NOT NULL,[CoverageFrom] date NOT NULL,[CoverageTo] date NOT NULL,[EmployeeCodeSnapshot] nvarchar(32) NOT NULL,[EmployeeNameSnapshot] nvarchar(220) NOT NULL,[JobTitleSnapshot] nvarchar(150) NULL,[DepartmentSnapshot] nvarchar(150) NULL,[ContractId] uniqueidentifier NULL,[ContractCodeSnapshot] nvarchar(40) NULL,[CurrencyId] uniqueidentifier NOT NULL,[CurrencyCodeSnapshot] nvarchar(8) NOT NULL,[CurrencySymbolSnapshot] nvarchar(12) NULL,[CurrencyDecimalPlacesSnapshot] tinyint NOT NULL,[ConfiguredBasicSalarySnapshot] decimal(19,4) NOT NULL,[CalculatedBasicSalary] decimal(19,4) NOT NULL,[GrossEarnings] decimal(19,4) NOT NULL,[TotalDeductions] decimal(19,4) NOT NULL,[TotalEmployerContributions] decimal(19,4) NOT NULL,[NetPay] decimal(19,4) NOT NULL,[BaseGrossEarnings] decimal(19,4) NOT NULL,[BaseDeductions] decimal(19,4) NOT NULL,[BaseEmployerContributions] decimal(19,4) NOT NULL,[BaseNetPay] decimal(19,4) NOT NULL,[Status] tinyint NOT NULL,[ReviewedBy] nvarchar(64) NULL,[ReviewedAtUtc] datetimeoffset NULL,[ApprovedBy] nvarchar(64) NULL,[ApprovedAtUtc] datetimeoffset NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_EmployeePayrolls] PRIMARY KEY([Id]),CONSTRAINT [CK_EmployeePayrolls_Coverage] CHECK([CoverageTo]>=[CoverageFrom]),CONSTRAINT [CK_EmployeePayrolls_Totals] CHECK([ConfiguredBasicSalarySnapshot]>=0 AND [CalculatedBasicSalary]>=0 AND [GrossEarnings]>=0 AND [TotalDeductions]>=0 AND [TotalEmployerContributions]>=0 AND [NetPay]>=0 AND [BaseGrossEarnings]>=0 AND [BaseDeductions]>=0 AND [BaseEmployerContributions]>=0 AND [BaseNetPay]>=0),CONSTRAINT [FK_EmployeePayrolls_Run] FOREIGN KEY([PayrollRunId]) REFERENCES [hr].[PayrollRuns]([Id]),CONSTRAINT [FK_EmployeePayrolls_Period] FOREIGN KEY([PayrollPeriodId]) REFERENCES [hr].[PayrollPeriods]([Id]),CONSTRAINT [FK_EmployeePayrolls_Employee] FOREIGN KEY([EmployeeId]) REFERENCES [hr].[Employees]([Id]),CONSTRAINT [FK_EmployeePayrolls_Contract] FOREIGN KEY([ContractId]) REFERENCES [hr].[EmployeeContracts]([Id]),CONSTRAINT [FK_EmployeePayrolls_Currency] FOREIGN KEY([CurrencyId]) REFERENCES [dbo].[tbl_Currencies]([Id]));
 CREATE UNIQUE INDEX [UX_EmployeePayroll_Run_Employee] ON [hr].[EmployeePayrolls]([PayrollRunId],[EmployeeId]);CREATE UNIQUE INDEX [UX_EmployeePayroll_Period_Employee] ON [hr].[EmployeePayrolls]([PayrollPeriodId],[EmployeeId]) WHERE [Status] <> 5;CREATE INDEX [IX_EmployeePayroll_Employee] ON [hr].[EmployeePayrolls]([EmployeeId]);CREATE INDEX [IX_EmployeePayroll_Status] ON [hr].[EmployeePayrolls]([Status]);
END;
IF OBJECT_ID(N'[hr].[EmployeePayrollSalarySegments]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[EmployeePayrollSalarySegments]([Id] uniqueidentifier NOT NULL,[EmployeePayrollId] uniqueidentifier NOT NULL,[ContractId] uniqueidentifier NULL,[ContractCodeSnapshot] nvarchar(40) NULL,[SalaryStructureId] uniqueidentifier NOT NULL,[SalaryStructureCodeSnapshot] nvarchar(40) NOT NULL,[EffectiveFrom] date NOT NULL,[EffectiveTo] date NOT NULL,[BasicSalaryRateSnapshot] decimal(19,4) NOT NULL,[ProrationFactor] decimal(18,8) NOT NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_EmployeePayrollSalarySegments] PRIMARY KEY([Id]),CONSTRAINT [CK_PayrollSalarySegments_Dates] CHECK([EffectiveTo]>=[EffectiveFrom]),CONSTRAINT [CK_PayrollSalarySegments_Amounts] CHECK([BasicSalaryRateSnapshot]>=0 AND [ProrationFactor]>=0 AND [ProrationFactor]<=1),CONSTRAINT [FK_PayrollSalarySegments_Payroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]),CONSTRAINT [FK_PayrollSalarySegments_Contract] FOREIGN KEY([ContractId]) REFERENCES [hr].[EmployeeContracts]([Id]),CONSTRAINT [FK_PayrollSalarySegments_Structure] FOREIGN KEY([SalaryStructureId]) REFERENCES [hr].[EmployeeSalaryStructures]([Id]));CREATE INDEX [IX_PayrollSalarySegments_Payroll] ON [hr].[EmployeePayrollSalarySegments]([EmployeePayrollId]);
END;
IF OBJECT_ID(N'[hr].[EmployeePayrollLines]',N'U') IS NULL BEGIN
 CREATE TABLE [hr].[EmployeePayrollLines]([Id] uniqueidentifier NOT NULL,[EmployeePayrollId] uniqueidentifier NOT NULL,[LineSequence] int NOT NULL,[SalaryStructureId] uniqueidentifier NULL,[SalaryComponentId] uniqueidentifier NULL,[ComponentCodeSnapshot] nvarchar(32) NULL,[ComponentNameSnapshot] nvarchar(150) NOT NULL,[ComponentType] tinyint NOT NULL,[SourceType] tinyint NOT NULL,[SourceModule] nvarchar(50) NULL,[SourceDocumentType] nvarchar(80) NULL,[SourceDocumentId] uniqueidentifier NULL,[SourceDate] date NULL,[Quantity] decimal(18,4) NULL,[Rate] decimal(19,6) NULL,[Amount] decimal(19,4) NOT NULL,[DebitPostingRole] nvarchar(50) NULL,[CreditPostingRole] nvarchar(50) NULL,[Description] nvarchar(500) NULL,[CreatedAtUtc] datetimeoffset NOT NULL,[CreatedBy] nvarchar(64) NULL,[LastModifiedAtUtc] datetimeoffset NULL,[LastModifiedBy] nvarchar(64) NULL,[CreatedFromDevice] nvarchar(256) NULL,[UpdatedFromDevice] nvarchar(256) NULL,[RowVersion] rowversion NOT NULL,CONSTRAINT [PK_EmployeePayrollLines] PRIMARY KEY([Id]),CONSTRAINT [CK_EmployeePayrollLines_Amount] CHECK([Amount]>=0),CONSTRAINT [FK_EmployeePayrollLines_Payroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]),CONSTRAINT [FK_EmployeePayrollLines_Structure] FOREIGN KEY([SalaryStructureId]) REFERENCES [hr].[EmployeeSalaryStructures]([Id]),CONSTRAINT [FK_EmployeePayrollLines_Component] FOREIGN KEY([SalaryComponentId]) REFERENCES [hr].[SalaryComponents]([Id]));CREATE UNIQUE INDEX [UX_EmployeePayrollLines_Payroll_Sequence] ON [hr].[EmployeePayrollLines]([EmployeePayrollId],[LineSequence]);CREATE INDEX [IX_EmployeePayrollLines_Source] ON [hr].[EmployeePayrollLines]([SourceType],[SourceDocumentId]);
END;
IF COL_LENGTH('hr.AttendanceRecords','EmployeePayrollId') IS NULL ALTER TABLE [hr].[AttendanceRecords] ADD [EmployeePayrollId] uniqueidentifier NULL;
""");

  m.Sql("""
SET XACT_ABORT ON;
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_Attendance_EmployeePayroll') ALTER TABLE [hr].[AttendanceRecords] ADD CONSTRAINT [FK_Attendance_EmployeePayroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Attendance_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[AttendanceRecords]')) CREATE INDEX [IX_Attendance_EmployeePayrollId] ON [hr].[AttendanceRecords]([EmployeePayrollId]);
IF COL_LENGTH('hr.OvertimeRecords','EmployeePayrollId') IS NULL ALTER TABLE [hr].[OvertimeRecords] ADD [EmployeePayrollId] uniqueidentifier NULL;
""");

  m.Sql("""
SET XACT_ABORT ON;
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_Overtime_EmployeePayroll') ALTER TABLE [hr].[OvertimeRecords] ADD CONSTRAINT [FK_Overtime_EmployeePayroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Overtime_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[OvertimeRecords]')) CREATE INDEX [IX_Overtime_EmployeePayrollId] ON [hr].[OvertimeRecords]([EmployeePayrollId]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_LoanInstallments_EmployeePayroll') ALTER TABLE [hr].[EmployeeLoanInstallments] ADD CONSTRAINT [FK_LoanInstallments_EmployeePayroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_LoanInstallments_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[EmployeeLoanInstallments]')) CREATE INDEX [IX_LoanInstallments_EmployeePayrollId] ON [hr].[EmployeeLoanInstallments]([EmployeePayrollId]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_EmployeeAdjustments_EmployeePayroll') ALTER TABLE [hr].[EmployeeAdjustments] ADD CONSTRAINT [FK_EmployeeAdjustments_EmployeePayroll] FOREIGN KEY([EmployeePayrollId]) REFERENCES [hr].[EmployeePayrolls]([Id]);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Adjustments_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[EmployeeAdjustments]')) CREATE INDEX [IX_Adjustments_EmployeePayrollId] ON [hr].[EmployeeAdjustments]([EmployeePayrollId]);
""");
 }

 protected override void Down(MigrationBuilder m)=>m.Sql("""
SET XACT_ABORT ON;
IF EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_EmployeeAdjustments_EmployeePayroll') ALTER TABLE [hr].[EmployeeAdjustments] DROP CONSTRAINT [FK_EmployeeAdjustments_EmployeePayroll];
IF EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_LoanInstallments_EmployeePayroll') ALTER TABLE [hr].[EmployeeLoanInstallments] DROP CONSTRAINT [FK_LoanInstallments_EmployeePayroll];
IF EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_Overtime_EmployeePayroll') ALTER TABLE [hr].[OvertimeRecords] DROP CONSTRAINT [FK_Overtime_EmployeePayroll];
IF EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_Attendance_EmployeePayroll') ALTER TABLE [hr].[AttendanceRecords] DROP CONSTRAINT [FK_Attendance_EmployeePayroll];
IF EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Attendance_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[AttendanceRecords]')) DROP INDEX [IX_Attendance_EmployeePayrollId] ON [hr].[AttendanceRecords];
IF EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Overtime_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[OvertimeRecords]')) DROP INDEX [IX_Overtime_EmployeePayrollId] ON [hr].[OvertimeRecords];
IF EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_LoanInstallments_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[EmployeeLoanInstallments]')) DROP INDEX [IX_LoanInstallments_EmployeePayrollId] ON [hr].[EmployeeLoanInstallments];
IF EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Adjustments_EmployeePayrollId' AND object_id=OBJECT_ID(N'[hr].[EmployeeAdjustments]')) DROP INDEX [IX_Adjustments_EmployeePayrollId] ON [hr].[EmployeeAdjustments];
IF OBJECT_ID(N'[hr].[EmployeePayrollLines]',N'U') IS NOT NULL DROP TABLE [hr].[EmployeePayrollLines];IF OBJECT_ID(N'[hr].[EmployeePayrollSalarySegments]',N'U') IS NOT NULL DROP TABLE [hr].[EmployeePayrollSalarySegments];IF OBJECT_ID(N'[hr].[EmployeePayrolls]',N'U') IS NOT NULL DROP TABLE [hr].[EmployeePayrolls];IF OBJECT_ID(N'[hr].[PayrollRuns]',N'U') IS NOT NULL DROP TABLE [hr].[PayrollRuns];IF OBJECT_ID(N'[hr].[PayrollPeriods]',N'U') IS NOT NULL DROP TABLE [hr].[PayrollPeriods];IF OBJECT_ID(N'[hr].[PayrollPolicies]',N'U') IS NOT NULL DROP TABLE [hr].[PayrollPolicies];
IF COL_LENGTH('hr.OvertimeRecords','EmployeePayrollId') IS NOT NULL ALTER TABLE [hr].[OvertimeRecords] DROP COLUMN [EmployeePayrollId];IF COL_LENGTH('hr.AttendanceRecords','EmployeePayrollId') IS NOT NULL ALTER TABLE [hr].[AttendanceRecords] DROP COLUMN [EmployeePayrollId];IF COL_LENGTH('hr.EmployeeContracts','TerminationEffectiveDate') IS NOT NULL ALTER TABLE [hr].[EmployeeContracts] DROP COLUMN [TerminationEffectiveDate];
IF EXISTS(SELECT 1 FROM sys.sequences WHERE name=N'PayrollRunCodeSequence' AND schema_id=SCHEMA_ID(N'hr')) DROP SEQUENCE [hr].[PayrollRunCodeSequence];IF EXISTS(SELECT 1 FROM sys.sequences WHERE name=N'PayrollPolicyCodeSequence' AND schema_id=SCHEMA_ID(N'hr')) DROP SEQUENCE [hr].[PayrollPolicyCodeSequence];
""");
}
